#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "1 particles" "/run/beamOn 1"
/gui/addButton run "10 particle" "/run/beamOn 10"
/gui/addButton run "100 particles" "/run/beamOn 100"
/gui/addButton run "1000 particles" "/run/beamOn 1000"
/gui/addButton run "run.mac" "/control/execute run.mac"
#
# Gun menu :
/gui/addMenu gun Energy
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "100 MeV"  "/gun/energy 100 MeV"
/gui/addButton gun "200 MeV"  "/gun/energy 200 MeV"
/gui/addButton gun "500 MeV"  "/gun/energy 500 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "20 GeV"  "/gun/energy 20 GeV"
/gui/addButton gun "50 GeV"  "/gun/energy 50 GeV"
/gui/addButton gun "100 GeV"  "/gun/energy 100 GeV"

/gui/addMenu particle Particle
/gui/addButton particle "e-"      "/gun/particle e-"
/gui/addButton particle "e+"      "/gun/particle e+"
/gui/addButton particle "photon"      "/gun/particle gamma"
/gui/addButton particle "pi0"     "/gun/particle pi0"
/gui/addButton particle "pi+"     "/gun/particle pi+"
/gui/addButton particle "neutron" "/gun/particle neutron"
/gui/addButton particle "proton"  "/gun/particle proton"
#
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
/run/printProgress 100
#
